"""
VERC - Volume Expansion Range Compression Strategy

Detects stocks that are quietly being accumulated by institutions before a breakout.
Identifies stocks where:
- Price volatility decreases
- Trading range tightens
- Volume gradually expands

This pattern often precedes large directional moves.
"""

import pandas as pd
import numpy as np
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass


@dataclass
class VERCSignal:
    """Signal generated by the VERC strategy"""
    stock_symbol: str
    compression_detected: bool
    breakout_detected: bool
    current_price: float
    compression_high: float
    compression_low: float
    range_height: float
    entry_min: float
    entry_max: float
    stop_loss: float
    target_1: float
    target_2: float
    confidence_score: int
    confidence_factors: Dict[str, int]
    volume_ratio: float
    relative_volume: float
    trend_aligned: bool


def calculate_atr(df: pd.DataFrame, period: int = 14) -> pd.Series:
    """
    Calculate Average True Range (ATR)
    
    Args:
        df: DataFrame with 'high', 'low', 'close' columns
        period: ATR period (default: 14)
    
    Returns:
        Series with ATR values
    """
    high = df['high']
    low = df['low']
    close = df['close']
    
    tr1 = high - low
    tr2 = abs(high - close.shift(1))
    tr3 = abs(low - close.shift(1))
    
    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
    atr = tr.rolling(window=period).mean()
    
    return atr


def calculate_volume_ma(df: pd.DataFrame, period: int) -> pd.Series:
    """
    Calculate Volume Moving Average
    
    Args:
        df: DataFrame with 'volume' column
        period: MA period
    
    Returns:
        Series with MA values
    """
    return df['volume'].rolling(window=period).mean()


def detect_range_compression(
    df: pd.DataFrame,
    lookback: int = 20,
    compression_threshold: float = 0.05
) -> Tuple[bool, float, float]:
    """
    Detect if price is in a compressed range.
    
    Rules:
    - Highest High (last N candles) - Lowest Low (last N candles) < 5% of current price
    - OR ATR(14) is lowest in last 30 candles
    
    Args:
        df: DataFrame with 'high', 'low', 'close' columns
        lookback: Number of candles to check for range (default: 20)
        compression_threshold: Max range as percentage of price (default: 0.05 = 5%)
    
    Returns:
        Tuple of (compression_detected, range_high, range_low)
    """
    if len(df) < lookback:
        return False, 0.0, 0.0
    
    recent_df = df.tail(lookback)
    current_price = df['close'].iloc[-1]
    
    # Calculate highest high and lowest low for the lookback period
    range_high = recent_df['high'].max()
    range_low = recent_df['low'].min()
    range_height = range_high - range_low
    range_percentage = range_height / current_price
    
    # Check if range is compressed
    compression_detected = range_percentage < compression_threshold
    
    # Also check ATR condition (ATR is lowest in last 30 candles)
    if len(df) >= 30:
        atr = calculate_atr(df, 14)
        recent_30_atr = atr.tail(30)
        current_atr = atr.iloc[-1]
        
        # If ATR is at local minimum, consider it compression
        if current_atr == recent_30_atr.min():
            compression_detected = True
    
    return compression_detected, range_high, range_low


def detect_volume_expansion(
    df: pd.DataFrame,
    short_period: int = 5,
    long_period: int = 20,
    min_relative_volume: float = 1.3
) -> Tuple[bool, float, float]:
    """
    Detect volume expansion while price compresses.
    
    Rules:
    - Volume MA(5) > Volume MA(20)
    - OR Relative Volume > 1.3
    
    Args:
        df: DataFrame with 'volume' column
        short_period: Short MA period (default: 5)
        long_period: Long MA period (default: 20)
        min_relative_volume: Minimum relative volume threshold (default: 1.3)
    
    Returns:
        Tuple of (volume_expansion_detected, volume_ma_short, relative_volume)
    """
    if len(df) < long_period:
        return False, 0.0, 0.0
    
    volume_ma_short = calculate_volume_ma(df, short_period).iloc[-1]
    volume_ma_long = calculate_volume_ma(df, long_period).iloc[-1]
    current_volume = df['volume'].iloc[-1]
    
    # Calculate Volume MA30 for relative volume
    volume_ma30 = calculate_volume_ma(df, 30).iloc[-1] if len(df) >= 30 else volume_ma_long
    relative_volume = current_volume / volume_ma30 if volume_ma30 > 0 else 0
    
    # Check volume expansion conditions
    ma_expansion = volume_ma_short > volume_ma_long
    relative_volume_expansion = relative_volume > min_relative_volume
    
    volume_expansion_detected = ma_expansion or relative_volume_expansion
    
    return volume_expansion_detected, volume_ma_short, relative_volume


def detect_breakout(
    df: pd.DataFrame,
    compression_high: float,
    min_breakout_volume: float = None
) -> Tuple[bool, float]:
    """
    Detect breakout from compression range.
    
    Rules:
    - Close > Highest High of compression range
    - Breakout Volume > Volume MA30
    
    Args:
        df: DataFrame with 'close', 'volume' columns
        compression_high: Highest high of compression range
        min_breakout_volume: Minimum volume for breakout confirmation
    
    Returns:
        Tuple of (breakout_detected, breakout_price)
    """
    if len(df) < 2:
        return False, 0.0
    
    current_close = df['close'].iloc[-1]
    breakout_price = current_close
    
    # Check if price broke above compression range
    breakout_detected = current_close > compression_high
    
    # Check volume confirmation if threshold provided
    if breakout_detected and min_breakout_volume is not None:
        current_volume = df['volume'].iloc[-1]
        breakout_volume_confirmed = current_volume > min_breakout_volume
        breakout_detected = breakout_detected and breakout_volume_confirmed
    
    return breakout_detected, breakout_price


def check_trend_alignment(df: pd.DataFrame, short_ema: int = 20, long_ema: int = 50) -> bool:
    """
    Check if price is aligned with medium-term trend.
    
    Rules:
    - Price > EMA50
    - OR EMA20 > EMA50
    
    Args:
        df: DataFrame with 'close' column
        short_ema: Short EMA period (default: 20)
        long_ema: Long EMA period (default: 50)
    
    Returns:
        True if trend aligned, False otherwise
    """
    if len(df) < long_ema:
        return False
    
    current_close = df['close'].iloc[-1]
    
    # Calculate EMAs
    ema_short = df['close'].ewm(span=short_ema, adjust=False).mean().iloc[-1]
    ema_long = df['close'].ewm(span=long_ema, adjust=False).mean().iloc[-1]
    
    # Check trend alignment
    price_above_ema50 = current_close > ema_long
    ema_alignment = ema_short > ema_long
    
    return price_above_ema50 or ema_alignment


def calculate_confidence_score(
    compression_detected: bool,
    volume_expansion_detected: bool,
    breakout_detected: bool,
    trend_aligned: bool,
    relative_volume: float,
    range_percentage: float = None
) -> Tuple[int, Dict[str, int]]:
    """
    Calculate confidence score for the signal.
    
    Scoring:
    - Range Compression: +3
    - Volume Expansion: +2
    - Breakout Volume: +2
    - Index Trend Alignment: +2
    - Relative Strength: +1
    
    Alert threshold: Score >= 7
    
    Args:
        compression_detected: Whether range compression is detected
        volume_expansion_detected: Whether volume expansion is detected
        breakout_detected: Whether breakout has occurred
        trend_aligned: Whether price is trend-aligned
        relative_volume: Current relative volume
        range_percentage: Range as percentage of price
    
    Returns:
        Tuple of (total_score, factors_dict)
    """
    factors = {
        "Range Compression": 0,
        "Volume Expansion": 0,
        "Breakout Volume": 0,
        "Index Trend Alignment": 0,
        "Relative Strength": 0
    }
    
    # Range Compression: +3
    if compression_detected:
        factors["Range Compression"] = 3
    
    # Volume Expansion: +2
    if volume_expansion_detected:
        factors["Volume Expansion"] = 2
    
    # Breakout Volume: +2 (if relative volume > 1.5)
    if breakout_detected and relative_volume > 1.5:
        factors["Breakout Volume"] = 2
    elif breakout_detected:
        factors["Breakout Volume"] = 1
    
    # Index Trend Alignment: +2
    if trend_aligned:
        factors["Index Trend Alignment"] = 2
    
    # Relative Strength: +1 (if range is very tight < 3%)
    if range_percentage is not None and range_percentage < 0.03:
        factors["Relative Strength"] = 1
    
    total_score = sum(factors.values())
    
    return total_score, factors


def generate_signal(
    df: pd.DataFrame,
    stock_symbol: str,
    compression_lookback: int = 20,
    compression_threshold: float = 0.05,
    volume_lookback: int = 20,
    min_relative_volume: float = 1.3
) -> Optional[VERCSignal]:
    """
    Generate a VERC signal for a stock.
    
    Main function that orchestrates all detection functions.
    
    Args:
        df: DataFrame with OHLCV data (open, high, low, close, volume)
        stock_symbol: Stock ticker symbol
        compression_lookback: Lookback for compression detection
        compression_threshold: Threshold for compression detection
        volume_lookback: Lookback for volume analysis
        min_relative_volume: Minimum relative volume for expansion
    
    Returns:
        VERCSignal if conditions met, None otherwise
    """
    if len(df) < 30:
        return None
    
    current_price = df['close'].iloc[-1]
    
    # Detect range compression
    compression_detected, compression_high, compression_low = detect_range_compression(
        df, compression_lookback, compression_threshold
    )
    
    # Detect volume expansion
    volume_expansion_detected, volume_ma_short, relative_volume = detect_volume_expansion(
        df, 5, volume_lookback, min_relative_volume
    )
    
    # Check trend alignment
    trend_aligned = check_trend_alignment(df)
    
    # Get volume MA30 for breakout confirmation
    volume_ma30 = calculate_volume_ma(df, 30).iloc[-1]
    
    # Detect breakout
    breakout_detected, breakout_price = detect_breakout(
        df, compression_high, volume_ma30
    )
    
    # Calculate range percentage
    range_height = compression_high - compression_low
    range_percentage = range_height / current_price if current_price > 0 else 0
    
    # Calculate confidence score
    confidence_score, confidence_factors = calculate_confidence_score(
        compression_detected,
        volume_expansion_detected,
        breakout_detected,
        trend_aligned,
        relative_volume,
        range_percentage
    )
    
    # Only generate signal if confidence >= 7
    if confidence_score < 7:
        return None
    
    # Calculate entry zone (breakout price + 0.5% buffer)
    entry_min = compression_high
    entry_max = compression_high * 1.005
    
    # Calculate stop loss (below compression base)
    stop_loss = compression_low
    
    # Calculate targets (measured move)
    target_1 = compression_high + (range_height * 1)
    target_2 = compression_high + (range_height * 2)
    
    signal = VERCSignal(
        stock_symbol=stock_symbol,
        compression_detected=compression_detected,
        breakout_detected=breakout_detected,
        current_price=current_price,
        compression_high=compression_high,
        compression_low=compression_low,
        range_height=range_height,
        entry_min=entry_min,
        entry_max=entry_max,
        stop_loss=stop_loss,
        target_1=target_1,
        target_2=target_2,
        confidence_score=confidence_score,
        confidence_factors=confidence_factors,
        volume_ratio=volume_ma_short / calculate_volume_ma(df, volume_lookback).iloc[-1],
        relative_volume=relative_volume,
        trend_aligned=trend_aligned
    )
    
    return signal


def format_alert(signal: VERCSignal) -> str:
    """
    Format the signal as an alert message.
    
    Args:
        signal: VERCSignal to format
    
    Returns:
        Formatted alert string
    """
    alert_lines = [
        "ACCUMULATION BREAKOUT",
        "",
        f"Stock: {signal.stock_symbol}",
        "",
        "Compression Detected" if signal.compression_detected else "Watch List",
        f"Range: {signal.compression_low:.2f} – {signal.compression_high:.2f}",
        "",
        f"Entry: {signal.entry_min:.2f} – {signal.entry_max:.2f}",
        f"Stop: {signal.stop_loss:.2f}",
        "",
        f"Target 1: {signal.target_1:.2f}",
        f"Target 2: {signal.target_2:.2f}",
        "",
        f"Confidence: {signal.confidence_score}/10",
        "",
        "Factors:"
    ]
    
    for factor, score in signal.confidence_factors.items():
        if score > 0:
            alert_lines.append(f"  +{factor}: {score}")
    
    return "\n".join(alert_lines)


def scan_stocks(stocks_data: Dict[str, pd.DataFrame]) -> List[VERCSignal]:
    """
    Scan multiple stocks for VERC signals.
    
    Args:
        stocks_data: Dictionary of {symbol: DataFrame} pairs
    
    Returns:
        List of VERCSignal objects
    """
    signals = []
    
    for symbol, df in stocks_data.items():
        signal = generate_signal(df, symbol)
        if signal is not None:
            signals.append(signal)
    
    # Sort by confidence score (descending)
    signals.sort(key=lambda x: x.confidence_score, reverse=True)
    
    return signals


# Example usage and testing
if __name__ == "__main__":
    # Create sample data for testing
    np.random.seed(42)
    
    # Generate 60 days of sample data
    dates = pd.date_range(start="2024-01-01", periods=60, freq="D")
    
    # Create price data with compression pattern
    base_price = 500
    prices = []
    for i in range(60):
        if i < 40:
            # Compression phase - tight range
            price = base_price + np.random.uniform(-10, 10)
        else:
            # Breakout phase
            price = base_price + 15 + (i - 40) * 2
        prices.append(price)
    
    # Add some noise and trend
    prices = np.array(prices) + np.cumsum(np.random.randn(60) * 0.5)
    
    # Create DataFrame
    df = pd.DataFrame({
        'date': dates,
        'open': prices + np.random.uniform(-2, 2, 60),
        'high': prices + np.random.uniform(0, 5, 60),
        'low': prices - np.random.uniform(0, 5, 60),
        'close': prices,
        'volume': np.random.uniform(1000000, 5000000, 60)
    })
    
    # Increase volume in recent days (volume expansion)
    df.loc[45:, 'volume'] = df.loc[45:, 'volume'] * 1.5
    
    # Test the strategy
    signal = generate_signal(df, "TEST")
    
    if signal:
        print("Signal Generated!")
        print(f"Stock: {signal.stock_symbol}")
        print(f"Compression: {signal.compression_high:.2f} - {signal.compression_low:.2f}")
        print(f"Entry: {signal.entry_min:.2f} - {signal.entry_max:.2f}")
        print(f"Stop: {signal.stop_loss:.2f}")
        print(f"Target 1: {signal.target_1:.2f}")
        print(f"Target 2: {signal.target_2:.2f}")
        print(f"Confidence: {signal.confidence_score}/10")
        print()
        print(format_alert(signal))
    else:
        print("No signal generated")
