"""
Accumulation Detection Engine
Implements Wyckoff-style institutional accumulation detection
"""

import pandas as pd
import numpy as np
from typing import Dict, List, Optional
from dataclasses import dataclass
import logging

logger = logging.getLogger(__name__)


@dataclass
class AccumulationSignal:
    """Signal generated by the accumulation detector"""
    stock_symbol: str
    current_price: float
    
    # Price Structure
    in_range: bool
    range_high: float
    range_low: float
    range_days: int
    
    # Support/Resistance
    support_level: float
    support_touches: int
    resistance_level: float
    
    # Volatility
    atr_current: float
    atr_trend: str  # 'declining', 'stable', 'increasing'
    
    # Volume Pattern
    up_volume_ratio: float
    volume_spike_near_support: bool
    
    # Delivery Data
    delivery_trend: str  # 'increasing', 'stable', 'decreasing'
    delivery_current: float
    
    # Relative Strength
    rs_ratio: float  # Stock return / Index return
    rs_trend: str  # 'positive', 'neutral', 'negative'
    
    # Moving Averages
    price_above_ma50: bool
    ma50_slope: float
    ma50_trend: str  # 'up', 'flat', 'down'
    
    # Breakout Status
    near_breakout: bool
    breakout_distance_pct: float
    
    # Overall
    accumulation_detected: bool
    confidence_factors: Dict[str, bool]


class AccumulationDetector:
    """
    Detects institutional accumulation patterns using Wyckoff methodology
    """
    
    def __init__(self, config: Dict):
        self.config = config
        self.thresholds = config.get('scanner', {}).get('thresholds', {})
        self.lookback = config.get('scanner', {}).get('lookback', {})
        
    def analyze(
        self,
        symbol: str,
        price_data: pd.DataFrame,
        delivery_data: Optional[pd.DataFrame] = None,
        index_data: Optional[pd.DataFrame] = None
    ) -> AccumulationSignal:
        """
        Run complete accumulation analysis on a stock
        
        Args:
            symbol: Stock symbol
            price_data: OHLCV DataFrame
            delivery_data: Optional delivery percentage data
            index_data: Optional index data for RS calculation
            
        Returns:
            AccumulationSignal with all analysis results
        """
        if price_data is None or len(price_data) < 60:
            return self._empty_signal(symbol)
            
        signal = AccumulationSignal(
            stock_symbol=symbol,
            current_price=price_data['close'].iloc[-1],
            in_range=False,
            range_high=0,
            range_low=0,
            range_days=0,
            support_level=0,
            support_touches=0,
            resistance_level=0,
            atr_current=0,
            atr_trend='stable',
            up_volume_ratio=0,
            volume_spike_near_support=False,
            delivery_trend='stable',
            delivery_current=0,
            rs_ratio=0,
            rs_trend='neutral',
            price_above_ma50=False,
            ma50_slope=0,
            ma50_trend='flat',
            near_breakout=False,
            breakout_distance_pct=0,
            accumulation_detected=False,
            confidence_factors={}
        )
        
        # 1. Price Structure Analysis
        self._analyze_price_structure(price_data, signal)
        
        # 2. Support/Resistance Analysis
        self._analyze_support_resistance(price_data, signal)
        
        # 3. Volatility Analysis (ATR)
        self._analyze_volatility(price_data, signal)
        
        # 4. Volume Pattern Analysis
        self._analyze_volume_pattern(price_data, signal)
        
        # 5. Delivery Data Analysis
        if delivery_data is not None:
            self._analyze_delivery(delivery_data, signal)
            
        # 6. Relative Strength Analysis
        if index_data is not None:
            self._analyze_relative_strength(price_data, index_data, signal)
            
        # 7. Moving Average Analysis
        self._analyze_moving_averages(price_data, signal)
        
        # 8. Breakout Analysis
        self._analyze_breakout(price_data, signal)
        
        # 9. Final Determination
        self._determine_accumulation(signal)
        
        return signal
    
    def _empty_signal(self, symbol: str) -> AccumulationSignal:
        """Return an empty signal for insufficient data"""
        return AccumulationSignal(
            stock_symbol=symbol,
            current_price=0,
            in_range=False,
            range_high=0,
            range_low=0,
            range_days=0,
            support_level=0,
            support_touches=0,
            resistance_level=0,
            atr_current=0,
            atr_trend='stable',
            up_volume_ratio=0,
            volume_spike_near_support=False,
            delivery_trend='stable',
            delivery_current=0,
            rs_ratio=0,
            rs_trend='neutral',
            price_above_ma50=False,
            ma50_slope=0,
            ma50_trend='flat',
            near_breakout=False,
            breakout_distance_pct=0,
            accumulation_detected=False,
            confidence_factors={}
        )
    
    def _analyze_price_structure(
        self, 
        df: pd.DataFrame, 
        signal: AccumulationSignal
    ) -> None:
        """
        Analyze price structure for 30-90 day sideways range
        """
        min_days = self.lookback.get('min_range_days', 30)
        max_days = self.lookback.get('max_range_days', 90)
        max_range_pct = self.thresholds.get('max_range_percentage', 25)
        
        # Check multiple lookback periods
        for days in range(min_days, max_days + 1, 10):
            if len(df) < days:
                continue
                
            recent = df.tail(days)
            high = recent['high'].max()
            low = recent['low'].min()
            current = df['close'].iloc[-1]
            
            range_pct = ((high - low) / current) * 100
            
            if range_pct < max_range_pct:
                signal.in_range = True
                signal.range_high = high
                signal.range_low = low
                signal.range_days = days
                signal.confidence_factors['price_structure'] = True
                break
        else:
            signal.confidence_factors['price_structure'] = False
    
    def _analyze_support_resistance(
        self, 
        df: pd.DataFrame, 
        signal: AccumulationSignal
    ) -> None:
        """
        Find support and resistance levels with touch counts
        """
        if not signal.in_range:
            return
            
        current = signal.current_price
        support_deviation = self.thresholds.get('support_deviation', 3)
        
        # Find local lows for support
        lows = df['low'].tail(signal.range_days).values
        
        # Cluster similar low prices to find support levels
        supports = []
        for i, low in enumerate(lows):
            touch_count = 1
            for j, other in enumerate(lows):
                if i != j and abs(low - other) / low * 100 < support_deviation:
                    touch_count += 1
                    
            if touch_count >= 2:
                supports.append((low, touch_count))
        
        # Get strongest support
        if supports:
            supports.sort(key=lambda x: x[1], reverse=True)
            signal.support_level = supports[0][0]
            signal.support_touches = supports[0][1]
            
            # Check if price is near support (within 5%)
            if (current - signal.support_level) / current * 100 < 5:
                signal.confidence_factors['support_strength'] = signal.support_touches >= 3
        
        # Find resistance (recent high)
        highs = df['high'].tail(signal.range_days).values
        signal.resistance_level = max(highs)
    
    def _analyze_volatility(
        self, 
        df: pd.DataFrame, 
        signal: AccumulationSignal
    ) -> None:
        """
        Check if ATR is declining (volatility compression)
        """
        # Calculate ATR
        high = df['high']
        low = df['low']
        close = df['close']
        
        tr1 = high - low
        tr2 = abs(high - close.shift(1))
        tr3 = abs(low - close.shift(1))
        
        tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
        atr = tr.rolling(window=14).mean()
        
        signal.atr_current = atr.iloc[-1] if len(atr) > 0 else 0
        
        # Check ATR trend over last 10-20 days
        lookback = self.lookback.get('volume_analysis_days', 20)
        
        if len(atr) >= lookback:
            recent_atr = atr.tail(lookback).values
            early_atr = recent_atr[:5]
            late_atr = recent_atr[-5:]
            
            avg_early = np.mean(early_atr)
            avg_late = np.mean(late_atr)
            
            if avg_late < avg_early * 0.9:
                signal.atr_trend = 'declining'
                signal.confidence_factors['volatility_compression'] = True
            elif avg_late > avg_early * 1.1:
                signal.atr_trend = 'increasing'
            else:
                signal.atr_trend = 'stable'
    
    def _analyze_volume_pattern(
        self, 
        df: pd.DataFrame, 
        signal: AccumulationSignal
    ) -> None:
        """
        Analyze volume patterns - up days vs down days
        """
        lookback = self.lookback.get('volume_analysis_days', 20)
        
        if len(df) < lookback:
            return
            
        recent = df.tail(lookback)
        
        # Calculate up days and down days
        up_days = recent[recent['close'] > recent['open']]
        down_days = recent[recent['close'] < recent['open']]
        
        up_volume = up_days['volume'].sum()
        down_volume = down_days['volume'].sum()
        
        if down_volume > 0:
            signal.up_volume_ratio = up_volume / down_volume
        else:
            signal.up_volume_ratio = 2.0  # Strong if no down days
            
        # Check for volume spike near support
        if signal.support_touches > 0:
            # Check volume on days when price was near support
            near_support = recent[
                recent['low'] <= signal.support_level * 1.03
            ]
            
            if len(near_support) > 0:
                avg_volume = recent['volume'].mean()
                support_volume = near_support['volume'].mean()
                
                if support_volume > avg_volume * 1.3:
                    signal.volume_spike_near_support = True
                    signal.confidence_factors['volume_pattern'] = True
    
    def _analyze_delivery(
        self, 
        df: pd.DataFrame, 
        signal: AccumulationSignal
    ) -> None:
        """
        Analyze delivery percentage trends (India-specific)
        """
        if 'delivery_pct' not in df.columns:
            return
            
        lookback = self.lookback.get('delivery_analysis_days', 10)
        
        if len(df) < lookback:
            return
            
        recent = df.tail(lookback)
        
        signal.delivery_current = recent['delivery_pct'].iloc[-1]
        
        # Check delivery trend
        early_delivery = recent['delivery_pct'].iloc[:5].mean()
        late_delivery = recent['delivery_pct'].iloc[-5:].mean()
        
        if late_delivery > early_delivery * 1.05:
            signal.delivery_trend = 'increasing'
            signal.confidence_factors['delivery_data'] = signal.delivery_current >= 50
        elif late_delivery < early_delivery * 0.95:
            signal.delivery_trend = 'decreasing'
        else:
            signal.delivery_trend = 'stable'
    
    def _analyze_relative_strength(
        self, 
        stock_df: pd.DataFrame,
        index_df: pd.DataFrame,
        signal: AccumulationSignal
    ) -> None:
        """
        Calculate relative strength vs index (Nifty 50)
        """
        # If no index data, assume neutral performance
        if index_df is None or len(index_df) < 10:
            signal.rs_ratio = 1.0
            signal.rs_trend = 'neutral'
            return
        
        lookback = self.lookback.get('rs_analysis_days', 20)
        
        if len(stock_df) < lookback or len(index_df) < lookback:
            return
            
        # Calculate returns
        stock_returns = stock_df['close'].pct_change().tail(lookback)
        index_returns = index_df['close'].pct_change().tail(lookback)
        
        stock_cum_return = (1 + stock_returns).prod() - 1
        index_cum_return = (1 + index_returns).prod() - 1
        
        if index_cum_return != 0:
            signal.rs_ratio = stock_cum_return / index_cum_return
        else:
            signal.rs_ratio = 1.0
            
        # RS Trend
        if signal.rs_ratio > 1.2:
            signal.rs_trend = 'positive'
        elif signal.rs_ratio < 0.8:
            signal.rs_trend = 'negative'
        else:
            signal.rs_trend = 'neutral'
            
        signal.confidence_factors['relative_strength'] = signal.rs_trend == 'positive'
    
    def _analyze_moving_averages(
        self, 
        df: pd.DataFrame, 
        signal: AccumulationSignal
    ) -> None:
        """
        Analyze 50 DMA behavior
        """
        ma_period = 50
        
        if len(df) < ma_period + 10:
            return
            
        # Calculate 50 DMA
        ma50 = df['close'].rolling(window=ma_period).mean()
        
        current_price = signal.current_price
        current_ma = ma50.iloc[-1]
        
        signal.price_above_ma50 = current_price > current_ma
        
        # Calculate MA slope
        ma_values = ma50.tail(10).values
        if len(ma_values) >= 2:
            slope = (ma_values[-1] - ma_values[0]) / ma_values[0]
            signal.ma50_slope = slope
            
            if slope > 0.01:
                signal.ma50_trend = 'up'
            elif slope < -0.01:
                signal.ma50_trend = 'down'
            else:
                signal.ma50_trend = 'flat'
                
        # MA condition met
        signal.confidence_factors['ma_behavior'] = (
            signal.price_above_ma50 and 
            signal.ma50_trend in ['up', 'flat']
        )
    
    def _analyze_breakout(
        self, 
        df: pd.DataFrame, 
        signal: AccumulationSignal
    ) -> None:
        """
        Check if stock is near breakout
        """
        if not signal.in_range:
            return
            
        resistance = signal.resistance_level
        current = signal.current_price
        
        distance_pct = (resistance - current) / current * 100
        signal.breakout_distance_pct = distance_pct
        
        # Near breakout if within 5% of resistance
        threshold = self.thresholds.get('resistance_proximity', 5)
        signal.near_breakout = distance_pct < threshold
        
        if signal.near_breakout:
            signal.confidence_factors['breakout_setup'] = True
    
    def _determine_accumulation(self, signal: AccumulationSignal) -> None:
        """
        Determine if accumulation is detected based on all factors
        """
        # Count positive factors
        factors = signal.confidence_factors
        
        required_factors = [
            'price_structure',
            'support_strength',
            'volume_pattern',
            'ma_behavior'
        ]
        
        positive_count = sum(1 for f in required_factors if factors.get(f, False))
        
        # Must have at least 3 of 4 core factors
        signal.accumulation_detected = positive_count >= 3
        
        signal.confidence_factors['accumulation'] = signal.accumulation_detected


def calculate_all_signals(
    stocks: List[str],
    fetcher,
    config: Dict
) -> List[AccumulationSignal]:
    """
    Run accumulation detection on a list of stocks
    
    Args:
        stocks: List of stock symbols
        fetcher: Data fetcher instance
        config: Configuration dictionary
        
    Returns:
        List of AccumulationSignal objects
    """
    detector = AccumulationDetector(config)
    signals = []
    
    # Get index data once
    index_data = fetcher.get_index_data("^NSEI", period="3mo")
    
    for symbol in stocks:
        try:
            # Get stock data
            price_data = fetcher.get_stock_data(symbol, period="6mo")
            
            if price_data is None:
                continue
                
            # Get delivery data
            try:
                delivery_data = fetcher.get_delivery_data(symbol, days=30)
            except Exception:
                delivery_data = None
            
            # Run analysis
            signal = detector.analyze(
                symbol,
                price_data,
                delivery_data,
                index_data
            )
            
            if signal.accumulation_detected:
                signals.append(signal)
                
        except Exception as e:
            logger.error(f"Error analyzing {symbol}: {str(e)}")
            continue
            
    return signals
