"""
Accumulation Detection Engine
Implements Wyckoff-style institutional accumulation detection
"""

import logging
from dataclasses import dataclass
from typing import Dict, List, Optional

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


@dataclass
class AccumulationSignal:
    """Signal generated by the accumulation detector"""

    stock_symbol: str
    current_price: float

    # Price Structure
    in_range: bool
    range_high: float
    range_low: float
    range_days: int
    range_pct: float = 0.0

    # Support/Resistance
    support_level: float = 0.0
    support_touches: int = 0
    resistance_level: float = 0.0
    price_to_support_pct: float = 0.0

    # Volatility
    atr_current: float = 0.0
    atr_trend: str = "stable"  # 'declining', 'stable', 'increasing'

    # Volume Pattern
    up_volume_ratio: float = 0.0
    volume_spike_near_support: bool = False
    volume_pattern: str = "stable"  # 'declining', 'stable', 'chaotic'
    volume_compression_ratio: float = 1.0

    # Delivery Data
    delivery_trend: str = "stable"  # 'increasing', 'stable', 'decreasing', 'missing'
    delivery_current: float = 0.0
    delivery_available: bool = False

    # Relative Strength
    rs_ratio: float = 0.0  # Backward-compatible field; stores outperformance in %
    rs_trend: str = "neutral"  # 'positive', 'neutral', 'negative'
    rs_outperformance_pct: float = 0.0

    # Moving Averages
    price_above_ma50: bool = False
    ma50_slope: float = 0.0
    ma50_trend: str = "flat"  # 'up', 'flat', 'down'
    near_ma50: bool = False
    ma_distance_pct: float = 0.0

    # Breakout Status
    near_breakout: bool = False
    breakout_distance_pct: float = 0.0

    # Overall
    accumulation_detected: bool = False
    confidence_factors: Dict[str, bool] = None


class AccumulationDetector:
    """
    Detects institutional accumulation patterns using Wyckoff methodology
    """

    def __init__(self, config: Dict):
        self.config = config
        self.thresholds = config.get("scanner", {}).get("thresholds", {})
        self.lookback = config.get("scanner", {}).get("lookback", {})

    def analyze(
        self,
        symbol: str,
        price_data: pd.DataFrame,
        delivery_data: Optional[pd.DataFrame] = None,
        index_data: Optional[pd.DataFrame] = None,
    ) -> AccumulationSignal:
        """
        Run complete accumulation analysis on a stock
        """
        if price_data is None or len(price_data) < 60:
            return self._empty_signal(symbol)

        signal = self._empty_signal(symbol)
        signal.stock_symbol = symbol
        signal.current_price = float(price_data["close"].iloc[-1])

        self._analyze_price_structure(price_data, signal)
        self._analyze_support_resistance(price_data, signal)
        self._analyze_volatility(price_data, signal)
        self._analyze_volume_pattern(price_data, signal)

        if delivery_data is not None:
            self._analyze_delivery(delivery_data, signal)
        else:
            signal.delivery_trend = "missing"
            signal.delivery_available = False

        if index_data is not None:
            self._analyze_relative_strength(price_data, index_data, signal)
        else:
            signal.rs_ratio = 0.0
            signal.rs_outperformance_pct = 0.0
            signal.rs_trend = "neutral"

        self._analyze_moving_averages(price_data, signal)
        self._analyze_breakout(price_data, signal)
        self._determine_accumulation(signal)

        return signal

    def _empty_signal(self, symbol: str) -> AccumulationSignal:
        """Return an empty signal for insufficient data"""
        return AccumulationSignal(
            stock_symbol=symbol,
            current_price=0.0,
            in_range=False,
            range_high=0.0,
            range_low=0.0,
            range_days=0,
            range_pct=0.0,
            support_level=0.0,
            support_touches=0,
            resistance_level=0.0,
            price_to_support_pct=0.0,
            atr_current=0.0,
            atr_trend="stable",
            up_volume_ratio=0.0,
            volume_spike_near_support=False,
            volume_pattern="stable",
            volume_compression_ratio=1.0,
            delivery_trend="missing",
            delivery_current=0.0,
            delivery_available=False,
            rs_ratio=0.0,
            rs_trend="neutral",
            rs_outperformance_pct=0.0,
            price_above_ma50=False,
            ma50_slope=0.0,
            ma50_trend="flat",
            near_ma50=False,
            ma_distance_pct=0.0,
            near_breakout=False,
            breakout_distance_pct=0.0,
            accumulation_detected=False,
            confidence_factors={},
        )

    def _analyze_price_structure(self, df: pd.DataFrame, signal: AccumulationSignal) -> None:
        """
        Analyze price structure for 30-90 day sideways range using longest valid scan.
        """
        min_days = self.lookback.get("min_range_days", 30)
        max_days = self.lookback.get("max_range_days", 90)
        max_range_pct = self.thresholds.get("max_range_percentage", 25)

        signal.confidence_factors["price_structure"] = False

        for days in range(max_days, min_days - 1, -10):
            if len(df) < days:
                continue

            recent = df.tail(days)
            high = float(recent["high"].max())
            low = float(recent["low"].min())
            current = float(recent["close"].iloc[-1])

            if current <= 0:
                continue

            range_pct = ((high - low) / current) * 100

            if range_pct <= max_range_pct:
                signal.in_range = True
                signal.range_high = high
                signal.range_low = low
                signal.range_days = days
                signal.range_pct = float(range_pct)
                signal.confidence_factors["price_structure"] = True
                break

    def _analyze_support_resistance(self, df: pd.DataFrame, signal: AccumulationSignal) -> None:
        """
        Find support and resistance levels with distinct touch counts.
        Support touches use ±2% zone and require bounce-away before next touch.
        """
        signal.confidence_factors["support_strength"] = False

        if not signal.in_range or signal.range_days <= 0:
            return

        recent = df.tail(signal.range_days)
        lows = recent["low"].to_numpy(dtype=float)
        highs = recent["high"].to_numpy(dtype=float)

        if len(lows) == 0:
            return

        support_level = float(np.min(lows))
        resistance_level = float(np.max(highs))
        touches = self._count_distinct_support_touches(lows, support_level, deviation_pct=2.0, min_away_pct=2.0)

        signal.support_level = support_level
        signal.support_touches = touches
        signal.resistance_level = resistance_level

        if signal.current_price > 0 and support_level > 0:
            signal.price_to_support_pct = ((signal.current_price - support_level) / signal.current_price) * 100

        signal.confidence_factors["support_strength"] = touches >= 2

    def _analyze_volatility(self, df: pd.DataFrame, signal: AccumulationSignal) -> None:
        """
        Check ATR trend for volatility compression.
        """
        signal.confidence_factors["volatility_compression"] = False

        high = df["high"]
        low = df["low"]
        close = df["close"]

        tr1 = high - low
        tr2 = (high - close.shift(1)).abs()
        tr3 = (low - close.shift(1)).abs()
        tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
        atr = tr.rolling(window=14).mean()

        if len(atr.dropna()) == 0:
            return

        signal.atr_current = float(atr.iloc[-1])

        lookback = min(self.lookback.get("volume_analysis_days", 20), len(atr.dropna()))
        recent_atr = atr.dropna().tail(lookback)

        if len(recent_atr) < 6:
            return

        split = max(3, len(recent_atr) // 3)
        early_atr = recent_atr.iloc[:split].mean()
        late_atr = recent_atr.iloc[-split:].mean()

        if late_atr < early_atr * 0.92:
            signal.atr_trend = "declining"
            signal.confidence_factors["volatility_compression"] = True
        elif late_atr > early_atr * 1.08:
            signal.atr_trend = "increasing"
        else:
            signal.atr_trend = "stable"

    def _analyze_volume_pattern(self, df: pd.DataFrame, signal: AccumulationSignal) -> None:
        """
        Analyze volume behavior with compression/stability/chaos and support spikes.
        No directional up/down bias is used for gating.
        """
        signal.confidence_factors["volume_pattern"] = False

        lookback = self.lookback.get("volume_analysis_days", 20)
        if len(df) < lookback:
            return

        recent = df.tail(lookback).copy()
        volume = recent["volume"].astype(float)

        mean_volume = float(volume.mean()) if len(volume) else 0.0
        median_volume = float(volume.median()) if len(volume) else 0.0
        std_volume = float(volume.std()) if len(volume) > 1 else 0.0

        if mean_volume > 0:
            signal.volume_compression_ratio = std_volume / mean_volume
        else:
            signal.volume_compression_ratio = 1.0

        if len(volume) >= 6:
            split = max(3, len(volume) // 3)
            early_avg = float(volume.iloc[:split].mean())
            late_avg = float(volume.iloc[-split:].mean())
        else:
            early_avg = mean_volume
            late_avg = mean_volume

        if early_avg > 0 and late_avg < early_avg * 0.9 and signal.volume_compression_ratio <= 0.35:
            signal.volume_pattern = "declining"
        elif signal.volume_compression_ratio <= 0.5:
            signal.volume_pattern = "stable"
        else:
            signal.volume_pattern = "chaotic"

        up_days = recent[recent["close"] > recent["open"]]
        down_days = recent[recent["close"] < recent["open"]]
        up_volume = float(up_days["volume"].sum())
        down_volume = float(down_days["volume"].sum())
        signal.up_volume_ratio = (up_volume / down_volume) if down_volume > 0 else 1.0

        if signal.support_level > 0:
            near_support = recent[
                (recent["low"] >= signal.support_level * 0.98)
                & (recent["low"] <= signal.support_level * 1.02)
            ]
            if len(near_support) > 0 and median_volume > 0:
                support_avg_volume = float(near_support["volume"].mean())
                if support_avg_volume >= median_volume * 1.3:
                    signal.volume_spike_near_support = True

        signal.confidence_factors["volume_pattern"] = (
            signal.volume_pattern in ["declining", "stable"]
        )

    def _analyze_delivery(self, df: pd.DataFrame, signal: AccumulationSignal) -> None:
        """
        Analyze delivery percentage trends. Missing data stays neutral and never rejects.
        """
        if "delivery_pct" not in df.columns or len(df["delivery_pct"].dropna()) == 0:
            signal.delivery_trend = "missing"
            signal.delivery_available = False
            return

        recent = df["delivery_pct"].dropna().tail(self.lookback.get("delivery_analysis_days", 10))
        if len(recent) == 0:
            signal.delivery_trend = "missing"
            signal.delivery_available = False
            return

        signal.delivery_available = True
        signal.delivery_current = float(recent.iloc[-1])

        split = max(2, len(recent) // 2)
        early_delivery = float(recent.iloc[:split].mean())
        late_delivery = float(recent.iloc[-split:].mean())

        if late_delivery > early_delivery * 1.05:
            signal.delivery_trend = "increasing"
            signal.confidence_factors["delivery_data"] = signal.delivery_current >= 50
        elif late_delivery < early_delivery * 0.95:
            signal.delivery_trend = "decreasing"
            signal.confidence_factors["delivery_data"] = False
        else:
            signal.delivery_trend = "stable"
            signal.confidence_factors["delivery_data"] = signal.delivery_current >= 45

    def _analyze_relative_strength(
        self,
        stock_df: pd.DataFrame,
        index_df: pd.DataFrame,
        signal: AccumulationSignal,
    ) -> None:
        """
        Calculate relative strength using outperformance = stock_return - index_return.
        """
        signal.confidence_factors["relative_strength"] = False

        lookback = self.lookback.get("rs_analysis_days", 20)

        if index_df is None or len(stock_df) < lookback or len(index_df) < lookback:
            signal.rs_ratio = 0.0
            signal.rs_outperformance_pct = 0.0
            signal.rs_trend = "neutral"
            return

        stock_recent = stock_df["close"].tail(lookback)
        index_recent = index_df["close"].tail(lookback)

        stock_start = float(stock_recent.iloc[0])
        stock_end = float(stock_recent.iloc[-1])
        index_start = float(index_recent.iloc[0])
        index_end = float(index_recent.iloc[-1])

        if stock_start <= 0 or index_start <= 0:
            return

        stock_return = ((stock_end / stock_start) - 1) * 100
        index_return = ((index_end / index_start) - 1) * 100
        outperformance = stock_return - index_return

        signal.rs_outperformance_pct = float(outperformance)
        signal.rs_ratio = float(outperformance)

        if outperformance > 3:
            signal.rs_trend = "positive"
            signal.confidence_factors["relative_strength"] = True
        elif outperformance < -2:
            signal.rs_trend = "negative"
        else:
            signal.rs_trend = "neutral"

    def _analyze_moving_averages(self, df: pd.DataFrame, signal: AccumulationSignal) -> None:
        """
        Analyze 50 DMA behavior. near_ma means within ±5%.
        """
        signal.confidence_factors["ma_behavior"] = False

        ma_period = 50
        if len(df) < ma_period + 10:
            return

        ma50 = df["close"].rolling(window=ma_period).mean().dropna()
        if len(ma50) < 10:
            return

        current_ma = float(ma50.iloc[-1])
        current_price = signal.current_price

        if current_ma <= 0:
            return

        signal.ma_distance_pct = ((current_price - current_ma) / current_ma) * 100
        signal.near_ma50 = abs(signal.ma_distance_pct) <= 5
        signal.price_above_ma50 = current_price >= current_ma

        slope = (float(ma50.iloc[-1]) - float(ma50.iloc[0])) / float(ma50.iloc[0]) * 100
        signal.ma50_slope = float(slope)

        if slope > 1:
            signal.ma50_trend = "up"
        elif slope < -1:
            signal.ma50_trend = "down"
        else:
            signal.ma50_trend = "flat"

        signal.confidence_factors["ma_behavior"] = (
            (signal.price_above_ma50 and signal.ma50_trend in ["up", "flat"])
            or signal.near_ma50
        )

    def _count_distinct_support_touches(
        self,
        lows: np.ndarray,
        support_level: float,
        deviation_pct: float,
        min_away_pct: float = 2.0,
    ) -> int:
        """
        Count distinct support visits separated by a meaningful bounce away.
        """
        if support_level <= 0:
            return 0

        touches = 0
        ready_for_new_touch = True
        upper_zone = support_level * (1 + deviation_pct / 100)
        lower_zone = support_level * (1 - deviation_pct / 100)
        bounce_threshold = support_level * (1 + min_away_pct / 100)

        for low in lows:
            in_zone = lower_zone <= low <= upper_zone

            if in_zone and ready_for_new_touch:
                touches += 1
                ready_for_new_touch = False
            elif low > bounce_threshold:
                ready_for_new_touch = True

        return touches

    def _analyze_breakout(self, df: pd.DataFrame, signal: AccumulationSignal) -> None:
        """
        Check if stock is near breakout.
        """
        if not signal.in_range or signal.resistance_level <= 0 or signal.current_price <= 0:
            return

        resistance = signal.resistance_level
        current = signal.current_price

        distance_pct = ((resistance - current) / current) * 100
        signal.breakout_distance_pct = float(distance_pct)

        threshold = self.thresholds.get("resistance_proximity", 5)
        signal.near_breakout = distance_pct <= threshold

        if signal.near_breakout:
            signal.confidence_factors["breakout_setup"] = True

    def _determine_accumulation(self, signal: AccumulationSignal) -> None:
        """
        Soft accumulation gate uses only 4 factors and triggers at positive_count >= 3.
        """
        required_factors = [
            "price_structure",
            "support_strength",
            "volume_pattern",
            "ma_behavior",
        ]

        positive_count = sum(1 for factor in required_factors if signal.confidence_factors.get(factor, False))
        signal.accumulation_detected = positive_count >= 3
        signal.confidence_factors["accumulation"] = signal.accumulation_detected


def calculate_all_signals(
    stocks: List[str],
    fetcher,
    config: Dict,
) -> List[AccumulationSignal]:
    """
    Run accumulation detection on a list of stocks
    """
    detector = AccumulationDetector(config)
    signals = []

    index_data = fetcher.get_index_data("^NSEI", period="3mo")

    for symbol in stocks:
        try:
            price_data = fetcher.get_stock_data(symbol, period="6mo")

            if price_data is None:
                continue

            try:
                delivery_data = fetcher.get_delivery_data(symbol, days=30)
            except Exception:
                delivery_data = None

            signal = detector.analyze(symbol, price_data, delivery_data, index_data)

            if signal.accumulation_detected:
                signals.append(signal)

        except Exception as e:
            logger.error(f"Error analyzing {symbol}: {str(e)}")
            continue

    return signals